<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Borrow</name>
   <tag></tag>
   <elementGuidId>84cabc7f-f9e2-457b-81e2-e2ae9274faed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Borrow')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.text-decoration-none.text-dark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Borrow&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>599a8dbb-95a5-4361-893e-d68746db6fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8000/borrow</value>
      <webElementGuid>6ddcb0bd-5b47-42f5-b799-620f790eda52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-decoration-none  text-dark</value>
      <webElementGuid>9b730aa1-5b0b-4757-b57e-31627851f2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Borrow
        </value>
      <webElementGuid>93abfcd2-ba5d-4f9a-9a51-8bcb618d1ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/aside[@class=&quot;col-2 p-3&quot;]/ul[@class=&quot;list-unstyled&quot;]/li[@class=&quot;mt-4&quot;]/a[@class=&quot;text-decoration-none  text-dark&quot;]</value>
      <webElementGuid>35e88c5d-6de3-47fd-b4c7-7f1860129570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Borrow')]</value>
      <webElementGuid>ca2d61c7-bc45-4eef-ae2e-a6ff6e1be1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book'])[1]/following::a[1]</value>
      <webElementGuid>196a506a-ae86-4f19-8edb-d8ad94ef9206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jesslyn Book'])[1]/following::a[2]</value>
      <webElementGuid>990864d0-a09e-4bde-85e8-589d4e9724a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member'])[1]/preceding::a[1]</value>
      <webElementGuid>82574a36-ca61-4e69-99d0-92dde490b549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book'])[2]/preceding::a[2]</value>
      <webElementGuid>e30284af-32cc-4c04-9dac-423840037c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Borrow']/parent::*</value>
      <webElementGuid>60263daf-5364-4672-815c-0f13002bd667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8000/borrow']</value>
      <webElementGuid>514a5785-5fd0-4881-b452-2a500a73a86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>19dd8ea1-9593-4af1-960c-dc17dbaab3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost:8000/borrow' and (text() = '
            Borrow
        ' or . = '
            Borrow
        ')]</value>
      <webElementGuid>d4b24924-9de1-4ff5-81d7-896ea1dc5ac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
