<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Borrow_fad fa-pen-to-square text-white</name>
   <tag></tag>
   <elementGuidId>7e081e3c-c121-4ea8-b7c1-1ff19f8f1b0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example']/tbody/tr/td[8]/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fad.fa-pen-to-square.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; &quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>09380a70-05c0-4955-bda2-5e6a6c7d7c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fad fa-pen-to-square text-white</value>
      <webElementGuid>fc05e113-83a8-4795-8617-6ca341c56ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;d-flex align-items-center gap-2&quot;]/button[@class=&quot;btn btn-warning&quot;]/i[@class=&quot;fad fa-pen-to-square text-white&quot;]</value>
      <webElementGuid>d24a9fd2-0523-44ff-9965-4f79072de34d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example']/tbody/tr/td[8]/button[2]/i</value>
      <webElementGuid>e405c6d3-a80f-4c2d-9511-c52130fb14d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>a47ba8bd-d144-4dc8-8a12-c8e842c72786</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
